#!/bin/bash

echo "ESAT Master/Slave example"
echo "Author: denimlm/Mladenov"
echo "Initial release 0.1v"

echo "Current working directory is ${PWD}"
echo "Program start at "
date

# Argument validation check
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <run/debug> "
    exit 1
fi

if [ "$1" == "debug" ]; then
    #For Debug
    echo "#####################################"
    echo "QEMU: witing for debugger connection"
    ${PWD}/Tools/MinGW/qemu/qemu-system-arm -machine mps2-an385 -cpu cortex-m3 -kernel ${PWD}/FreeRTOSv202212.01/FreeRTOS/Demo/CORTEX_MPS2_QEMU_IAR_GCC/build/gcc/output/RTOSDemo.out -monitor none -nographic -serial stdio -s -S
else
    echo "#####################################"
    echo "QEMU: Simply start program Master/Slave"
    ${PWD}/Tools/MinGW/qemu/qemu-system-arm -machine mps2-an385 -cpu cortex-m3 -kernel ${PWD}/FreeRTOSv202212.01/FreeRTOS/Demo/CORTEX_MPS2_QEMU_IAR_GCC/build/gcc/output/RTOSDemo.out -monitor none -nographic -serial stdio
fi
